### ISSUE TITLE
모바일 대응

### ISSUE THREAD

**Issue by nevercaution** [yoonkiwoong/dublin#11]
대여장비는 모두 모바일 장비인데 리스트 목록을 잘 보여줄 수 있는게 좋아보입니다.

**Comment by yoonkiwoong** [comment]
대여 방법은 계속 고민중인데 현재는 카카오 대여 시스템 처럼 해당 웹페이지에서 필요한 장비를 미리 대여 신청 하고, QA팀에서 확인 후 대여 하는 방법으로 진행하려고 합니다. 그렇게 되면 모바일 화면보다 웹에서 볼 화면이 많을텐데, 그래도 모바일에서 더 잘 보이는 화면은 계속 고민해 보겠습니다.
