### ISSUE TITLE
장비목록 / 대여목록

### ISSUE THREAD

**Issue by blueshw** [yoonkiwoong/dublin#2]
장비목록이 곧 대여목록인거 같은데 왜 두가지가 다 필요한가요?
두 테이블은 합쳐도 될거 같은데...
대여여부를 `장비목록`에 붙이면 될거 같은데요.
@yoonkiwoong

**Comment by yoonkiwoong** [comment]
해당 페이지는 QA팀에서 장비 대여 기능과 함께 장비 관리 기능도 함께 수행해야 합니다.
따라서 목록은 장비 목록과 대여 목록 두 목록으로 분리하여 관리할 필요가 있습니다.

**Comment by blueshw** [comment]
장비 관리도 결국 `장비목록`에서 해도 무관한거 아닌가요?

**Comment by yoonkiwoong** [comment]
이는 QA팀 장비 관리 담당자와 인문팀 담당자에게 문의 했던 내용이라 나눠서 구현한 부분이 있습니다..만 
다시 한번 더 문의하여 하나로 합쳐도 상관 없는지 확인 하도록 하겠습니다.
