### ISSUE TITLE
장비 목록 [추가] 버튼> 하단에 [저장] 버튼이 아닌 [확인] 버튼으로 노출되는 현상

### ISSUE THREAD

**Issue by jinapark** [yoonkiwoong/dublin#22]
[상세 이슈]
장비 목록 [추가] 버튼> 하단에 [저장] 버튼이 아닌 [확인] 버튼으로 노출됩니다.

[발생 경로]
1. 장비 목록 진입
2. [추가] 버튼 선택
https://project-dublin.herokuapp.com/device/add
3. 하단 [확인] 버튼 확인

[기대 결과]
장비 목록 [추가] 버튼> 하단에 [저장] 버튼으로 노출되어야 합니다.

**Comment by yoonkiwoong** [comment]
해당 영역의 버튼을 저장으로 변경
