### ISSUE TITLE
장비 목록> 임의 장비 선택> 삭제하기시, 팝업 미노출되는 현상

### ISSUE THREAD

**Issue by jinapark** [yoonkiwoong/dublin#23]
[상세 이슈]
장비 목록> 임의 장비 선택> 삭제하기시, 팝업 미노출됩니다.(페이지로 노출됨)

[발생 경로]
1. 장비 목록 
2. 임의 장비 선택> 삭제 버튼 선택시, 팝업이 아닌 페이지로 노출됨을 확인

[기대 결과]
장비 목록> 임의 장비 선택> 삭제하기시, 팝업 노출되어야 합니다.

**Comment by yoonkiwoong** [comment]
수정 완료
