### ISSUE TITLE
[대여목록] 이름/버전이 같은 단말을 1대 대여시, 이름/ 버전이 같은 단말이 동시에 대여되는 현상 

### ISSUE THREAD

**Issue by jinapark** [yoonkiwoong/dublin#7]
[상세 이슈]
이름/버전이 같은 단말을 1대 대여시, 이름/ 버전이 같은 단말이 동시에 대여됩니다.

[발생 경로]
1. 장비 목록 페이지 진입
https://project-dublin.herokuapp.com/rental
2. 대여 목록 탭 선택
3. 이름 버전이 같은 단말 (iPhone5/8.1.1) 1개 단말 대여 선택
4. 대여 완료시, 대여 여부 확인

[기대 결과]
이름/버전이 같은 단말을 1대 대여시, 1대만 대여여부에 표시 되어야 합니다.

**Comment by yoonkiwoong** [comment]
수정되었습니다.
