### ISSUE TITLE
[대여목록] 단말 대여 완료시, 대여자/ 대여목록이 대여한 단말목록이 아닌 다른 단말에 노출되는 현상

### ISSUE THREAD

**Issue by jinapark** [yoonkiwoong/dublin#8]
[상세 이슈]
단말 대여 완료시, 대여자/ 대여목록이 대여한 단말목록이 아닌 다른 단말에 노출됩니다.

[발생 경로]
1. 장비 목록 웹페이지 진입
https://project-dublin.herokuapp.com/rental
2. 대여 목록탭 선택
3. 임의 단말 [대여가능] 버튼 선택
4. 대여 완료시, 대여목록 리스트에 대여자/ 대여 목록 정상적으로 노출되는지 여부 확인

[기대 결과]
단말 대여 완료시, 대여자/ 대여목록이 대여한 단말목록에 노출되어야 합니다.

**Comment by yoonkiwoong** [comment]
수정되었습니다.
