### ISSUE TITLE
수정 기능

### ISSUE THREAD

**Issue by hanhan86lee** [yoonkiwoong/dublin#9]
장비 목록 혹은 사용자 등록시 수정할 수 있는 기능이 없습니다.

**Comment by yoonkiwoong** [comment]
장비 등록 후 수정 기능은 추후 QA팀에서만 사용 할 수 있게 할 예정입니다.
로그인은 google 로그인 기능을 통해 특정 도메인을 가진 계정만 접속 가능하게 할 예정입니다.
